import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const file=path.join(process.cwd(),'phase9.html'),browser=await chromium.launch({headless:true}),page=await browser.newPage(),errors=[],consoleErrors=[],failedRequests=[];
page.on('pageerror',e=>errors.push({message:e.message,stack:e.stack||null}));
page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
page.on('requestfailed',r=>failedRequests.push(`${r.method()} ${r.url()} :: ${r.failure()?.errorText||'unknown'}`));
await page.goto(pathToFileURL(file).href,{waitUntil:'domcontentloaded',timeout:30000});
await page.waitForTimeout(1500);
await page.waitForFunction(()=>typeof GLOBAL_DATA!=='undefined'&&GLOBAL_DATA!==null,{timeout:15000});
const result=await page.evaluate(()=>{const script=[...document.scripts].map(s=>s.textContent||'').find(s=>s.includes('function calc'))||'',required=['carrier','category','device','ins','con','plan','data','devDisc'],controls=Object.fromEntries(required.map(id=>[id,!!document.getElementById(id)])),carriers=Object.keys(GLOBAL_DATA||{});return{carriers,scriptLength:script.length,calcMarker:script.indexOf('function calc'),calcCallable:typeof window.calc==='function',controls,allControlsPresent:Object.values(controls).every(Boolean)}});
console.log('[DIAG] page errors:',JSON.stringify(errors,null,2));
console.log('[DIAG] console errors:',JSON.stringify(consoleErrors,null,2));
console.log('[DIAG] failed requests:',JSON.stringify(failedRequests,null,2));
console.log('[DIAG] readiness:',JSON.stringify(result,null,2));
const output={errors,consoleErrors,failedRequests,...result};
fs.writeFileSync('calc-diagnostic.json',JSON.stringify(output,null,2));
await browser.close();
if(errors.length||consoleErrors.length||failedRequests.length||result.carriers.length!==6||!result.calcCallable||!result.allControlsPresent)process.exit(1);
