import { chromium } from 'playwright';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
const OLD='https://raw.githubusercontent.com/oppominami8670/Simulator202603/main/index.html',NEW=pathToFileURL(path.join(process.cwd(),'phase9.html')).href,CASES=100,report={cases:[],summary:{}};
const money=x=>Number(String(x??'').replace(/[^0-9.-]/g,''));
const rng=(()=>{let x=0x6d2b79f5;return()=>{x|=0;x=Math.imul(x+0x6d2b79f5,1);let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}})();
async function load(p,u,n){const e=[],c=[],f=[];p.on('pageerror',x=>e.push(x.message));p.on('console',m=>{if(m.type()==='error')c.push(m.text())});p.on('requestfailed',r=>f.push(`${r.method()} ${r.url()} :: ${r.failure()?.errorText||'unknown'}`));await p.goto(u,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(1500);return{name:n,status:e.length||c.length||f.length?'FAIL':'PASS',errors:e,consoleErrors:c,failed:f}}
async function initLegacy(p){await p.waitForFunction(()=>typeof GLOBAL_DATA!=='undefined'&&GLOBAL_DATA!==null,{timeout:15000});await p.evaluate(async()=>{const w=m=>new Promise(r=>setTimeout(r,m));if(!document.querySelector('.sim-card')&&typeof addSimulator==='function')addSimulator();for(let i=0;i<60&&!document.querySelector('.sim-card');i++)await w(100);if(!document.querySelector('.sim-card')||typeof updateCalculations!=='function')throw Error('legacy calculator could not be initialized')})}
async function legacyCase(p,seed){return p.evaluate(async seed=>{const w=m=>new Promise(r=>setTimeout(r,m)),pick=(q,r)=>{const s=document.querySelector(`.sim-card ${q}`),a=[...(s?.options||[])].filter(o=>!o.disabled&&o.value!=='');if(!s||!a.length)throw Error(`legacy selector unavailable: ${q}`);const o=a[Math.min(a.length-1,Math.floor(r*a.length))];s.value=o.value;s.dispatchEvent(new Event('change',{bubbles:true}));return{value:o.value,text:o.textContent.trim()}};const cats=[...document.querySelectorAll('.sim-card .cat-btns .btn')],cat=cats[Math.min(cats.length-1,Math.floor(seed*cats.length))];if(!cat)throw Error('legacy category unavailable');const carrier=pick('.carrier-sel',seed);cat.click();await w(50);const category=cat.dataset.cat,device=pick('.dev-name',seed*1.31%1);await w(50);const ins=pick('.ins-count',seed*1.71%1);await w(50);const con=pick('.con-type',seed*2.13%1);await w(50);const plan=pick('.plan-sel',seed*2.71%1);await w(50);const data=pick('.data-sel',seed*3.17%1);const d=document.querySelector('.sim-card .dev-disc-input'),devDisc=Math.floor(seed*6)*5000;d.value=String(devDisc);d.dispatchEvent(new Event('input',{bubbles:true}));d.dispatchEvent(new Event('change',{bubbles:true}));updateCalculations();await w(100);const first=money(document.querySelector('.sim-card .final-1')?.textContent),later=money(document.querySelector('.sim-card .final-2')?.textContent);if(!Number.isFinite(first)||!Number.isFinite(later))throw Error(`legacy result invalid ${first}/${later}`);return{carrier,category,device,ins,con,plan,data,devDisc,first,later}},seed)}
async function newCase(p,input){return p.evaluate(async input=>{const w=m=>new Promise(r=>setTimeout(r,m)),set=(id,value,text)=>{const s=document.getElementById(id),o=[...(s?.options||[])].find(x=>x.value===value)||[...(s?.options||[])].find(x=>x.textContent.trim()===text);if(!s||!o)throw Error(`new #${id}: no matching option`);s.value=o.value;s.dispatchEvent(new Event('change',{bubbles:true}))};set('carrier',input.carrier.value,input.carrier.text);await w(50);set('category',input.category,input.category);await w(50);set('device',input.device.value,input.device.text);await w(50);set('ins',input.ins.value,input.ins.text);await w(50);set('con',input.con.value,input.con.text);await w(50);set('plan',input.plan.value,input.plan.text);await w(50);set('data',input.data.value,input.data.text);const d=document.getElementById('devDisc');d.value=String(input.devDisc);d.dispatchEvent(new Event('input',{bubbles:true}));d.dispatchEvent(new Event('change',{bubbles:true}));const r=window.calc();if(!r||!Number.isFinite(r.first)||!Number.isFinite(r.later))throw Error('new calc result invalid');return{first:r.first,later:r.later}},input)}
const b=await chromium.launch({headless:true}),op=await b.newPage(),np=await b.newPage();try{report.oldLoad=await load(op,OLD,'old');report.newLoad=await load(np,NEW,'new');await initLegacy(op);await np.waitForFunction(()=>typeof GLOBAL_DATA!=='undefined'&&GLOBAL_DATA&&Object.keys(GLOBAL_DATA).length>0,null,{timeout:15000});report.master=Object.keys(await np.evaluate(()=>GLOBAL_DATA||{})).length;for(let i=1;i<=CASES;i++){try{const old=await legacyCase(op,rng()),fresh=await newCase(np,old),diff={first:fresh.first-old.first,later:fresh.later-old.later},item={index:i,status:diff.first===0&&diff.later===0?'PASS':'FAIL',input:{carrier:old.carrier,category:old.category,device:old.device,ins:old.ins,con:old.con,plan:old.plan,data:old.data,devDisc:old.devDisc},old:{first:old.first,later:old.later},new:fresh,diff};report.cases.push(item);if(item.status==='FAIL')console.error(`[PARITY] case ${i}: ${JSON.stringify(item)}`)}catch(e){const item={index:i,status:'FAIL',reason:e.stack||e.message};report.cases.push(item);console.error(`[PARITY] case ${i}: FAIL - ${item.reason}`)}}}catch(e){report.fatal=e.stack||e.message}finally{await b.close()}
const passed=report.cases.filter(x=>x.status==='PASS').length,failed=report.cases.length-passed;report.summary={generatedCases:report.cases.length,passedCases:passed,failedCases:failed,numericalParity:!report.fatal&&report.cases.length===CASES&&failed===0?'PASS':'FAIL',oldLoad:report.oldLoad?.status||'FAIL',newLoad:report.newLoad?.status||'FAIL',masterCarriers:report.master||0};fs.writeFileSync('numerical-parity-report.json',JSON.stringify(report,null,2));console.log('[PARITY] SUMMARY');console.log(JSON.stringify(report.summary,null,2));if(report.fatal)console.error(`[PARITY] FATAL: ${report.fatal}`);process.exit(report.summary.numericalParity==='PASS'&&report.summary.oldLoad==='PASS'&&report.summary.newLoad==='PASS'&&report.summary.masterCarriers===6?0:1);
