import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const OLD='https://raw.githubusercontent.com/oppominami8670/Simulator202603/main/index.html',NEW=pathToFileURL(path.join(process.cwd(),'phase9.html')).href,report={};
async function load(p,u,n){const e=[],c=[],f=[];p.on('pageerror',x=>e.push(x.message));p.on('console',m=>{if(m.type()==='error')c.push(m.text())});p.on('requestfailed',r=>f.push(`${r.method()} ${r.url()} :: ${r.failure()?.errorText||'unknown'}`));if(n==='old')await p.route('https://script.google.com/**',async route=>{try{const r=await fetch(route.request().url(),{redirect:'follow'});await route.fulfill({status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json'},body:await r.text()})}catch{await route.abort()}});await p.goto(u,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(1500);report[n]={status:e.length||c.length||f.length?'FAIL':'PASS',errors:e,consoleErrors:c,failed:f};return report[n].status==='PASS'}
async function initLegacy(p){await p.waitForFunction(()=>typeof GLOBAL_DATA!=='undefined'&&GLOBAL_DATA!==null,{timeout:15000});await p.evaluate(async()=>{const w=m=>new Promise(r=>setTimeout(r,m));if(!document.querySelector('.sim-card')&&typeof addSimulator==='function')addSimulator();for(let i=0;i<60&&!document.querySelector('.sim-card');i++)await w(100);if(!document.querySelector('.sim-card'))throw Error('legacy simulator card could not be initialized')})}
const b=await chromium.launch({headless:true}),op=await b.newPage(),np=await b.newPage();const oldLoad=await load(op,OLD,'old'),newLoad=await load(np,NEW,'new');let old={card:false,updateCalculations:false,controls:false};try{await initLegacy(op);old=await op.evaluate(()=>{const c=document.querySelector('.sim-card');return{card:!!c,updateCalculations:typeof updateCalculations==='function',controls:!!c?.querySelector('.carrier-sel')&&!!c?.querySelector('.dev-name')&&!!c?.querySelector('.plan-sel')}})}catch(e){old.reason=e.message}
await np.waitForFunction(()=>typeof GLOBAL_DATA!=='undefined'&&GLOBAL_DATA!==null,{timeout:15000});const ni=await np.evaluate(()=>({globalData:typeof GLOBAL_DATA!=='undefined'&&!!GLOBAL_DATA,carriers:Object.keys(GLOBAL_DATA||{}).length,calc:typeof calc==='function',controls:['carrier','category','device','ins','con','plan','data','devDisc'].every(id=>!!document.getElementById(id))}));let calc='FAIL',calcReason=null;try{await np.evaluate(async()=>{const w=m=>new Promise(r=>setTimeout(r,m)),s=id=>{const e=document.getElementById(id),o=[...(e?.options||[])].find(x=>!x.disabled&&x.value!=='');if(!e||!o)throw Error(`#${id} no usable option`);e.value=o.value;e.dispatchEvent(new Event('change',{bubbles:true}))};for(const id of ['carrier','category','device','ins','con','plan','data']){s(id);await w(100)};const r=window.calc();if(!r||!Number.isFinite(r.first)||!Number.isFinite(r.later))throw Error('calc result invalid')});calc='PASS'}catch(e){calcReason=e.message}
report.oldInterface={...old,status:old.card&&old.updateCalculations&&old.controls?'PASS':'FAIL'};report.newInterface={...ni,status:ni.globalData&&ni.carriers===6&&ni.calc&&ni.controls?'PASS':'FAIL',calc,calcReason};report.summary={oldLoad:oldLoad?'PASS':'FAIL',newLoad:newLoad?'PASS':'FAIL',oldInterface:report.oldInterface.status,newInterface:report.newInterface.status,newCalc:calc};fs.writeFileSync('regression-report.json',JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify(report.summary,null,2));process.exit(Object.values(report.summary).every(x=>x==='PASS')?0:1);
