import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const OLD='https://raw.githubusercontent.com/oppominami8670/Simulator202603/main/index.html',NEW=pathToFileURL(path.join(process.cwd(),'phase9.html')).href,report={};
async function load(p,u,n){const e=[],c=[],f=[];p.on('pageerror',x=>e.push(x.message));p.on('console',m=>{if(m.type()==='error')c.push(m.text())});p.on('requestfailed',r=>f.push(`${r.method()} ${r.url()} :: ${r.failure()?.errorText||'unknown'}`));if(n==='old'){const html=await (await fetch(OLD)).text();await p.setContent(html,{waitUntil:'domcontentloaded'});}else await p.goto(u,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForTimeout(1500);report[n]={status:e.length||c.length||f.length?'FAIL':'PASS',errors:e,consoleErrors:c,failed:f};return report[n].status==='PASS'}
async function initLegacy(p,master){await p.evaluate(async master=>{const w=m=>new Promise(r=>setTimeout(r,m));GLOBAL_DATA=master;if(!document.querySelector('.sim-card')&&typeof addSimulator==='function')addSimulator();for(let i=0;i<60&&!document.querySelector('.sim-card');i++)await w(100);if(!document.querySelector('.sim-card'))throw Error('legacy simulator card could not be initialized')},master)}
const b=await chromium.launch({headless:true}),op=await b.newPage(),np=await b.newPage();const oldLoad=await load(op,OLD,'old'),newLoad=await load(np,NEW,'new');await np.waitForFunction(()=>typeof GLOBAL_DATA!=='undefined'&&GLOBAL_DATA!==null,{timeout:15000});const master=await np.evaluate(()=>GLOBAL_DATA);let old={card:false,updateCalculations:false,controls:false};try{await initLegacy(op,master);old=await op.evaluate(()=>{const c=document.querySelector('.sim-card');return{card:!!c,updateCalculations:typeof updateCalculations==='function',controls:!!c?.querySelector('.carrier-sel')&&!!c?.querySelector('.dev-name')&&!!c?.querySelector('.plan-sel')}})}catch(e){old.reason=e.message}
const ni=await np.evaluate(()=>({globalData:typeof GLOBAL_DATA!=='undefined'&&!!GLOBAL_DATA,carriers:Object.keys(GLOBAL_DATA||{}).length,calc:typeof calc==='function',controls:['carrier','category','device','ins','con','plan','data','devDisc'].every(id=>!!document.getElementById(id))}));let calc='FAIL',calcReason=null;try{await np.evaluate(()=>{const carrier=Object.keys(GLOBAL_DATA).find(c=>(GLOBAL_DATA[c]?.devices||[]).some(x=>x[3]));if(!carrier)throw Error('no carrier with valid device contract data');const row=GLOBAL_DATA[carrier].devices.find(x=>x[3]);const plan=(GLOBAL_DATA[carrier].plans||[]).find(x=>x[0]);if(!plan)throw Error('no valid plan');$('carrier').value=carrier;$('category').value=row[0];$('device').innerHTML='';$('device').appendChild(new Option(row[1],row[1]));$('device').value=row[1];$('ins').innerHTML='';$('ins').appendChild(new Option(String(row[2]),String(row[2])));$('ins').value=String(row[2]);$('con').innerHTML='';$('con').appendChild(new Option(row[3],row[3]));$('con').value=row[3];$('plan').innerHTML='';$('plan').appendChild(new Option(plan[0],plan[0]));$('plan').value=plan[0];$('data').innerHTML='';$('data').appendChild(new Option(`${plan[1]} (${plan[2]}円)`,String(plan[2])));$('data').value=String(plan[2]);$('devDisc').value='0';const r=window.calc();if(!r||!Number.isFinite(r.first)||!Number.isFinite(r.later))throw Error('calc result invalid')});calc='PASS'}catch(e){calcReason=e.message}
report.oldInterface={...old,status:old.card&&old.updateCalculations&&old.controls?'PASS':'FAIL'};report.newInterface={...ni,status:ni.globalData&&ni.carriers===6&&ni.calc&&ni.controls?'PASS':'FAIL',calc,calcReason};report.summary={oldLoad:oldLoad?'PASS':'FAIL',newLoad:newLoad?'PASS':'FAIL',oldInterface:report.oldInterface.status,newInterface:report.newInterface.status,newCalc:calc};fs.writeFileSync('regression-report.json',JSON.stringify(report,null,2));await b.close();console.log(JSON.stringify(report.summary,null,2));process.exit(Object.values(report.summary).every(x=>x==='PASS')?0:1);
